# Generated by Django 6.0.8 on 2026-10-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(default=0)),
                ('api_url', models.URLField(blank=True)),
                ('node_uuid', models.UUIDField(blank=True, null=True)),
                ('cursor', models.CharField(blank=True, max_length=80)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_kind', models.CharField(blank=True, max_length=20)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
