# Generated by Django 6.0.8 on 2026-10-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsync', '0001_initial'),
        ('feedback', '0021_feedbacksubmission_respondent_ref_survey_inbox_since_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_uuid', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_status', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SurveySyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_through_sequence', models.PositiveBigIntegerField(default=0)),
                ('abandoned_sequences', models.JSONField(blank=True, default=list)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='feedback.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SyncedSubmissionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_version', models.PositiveIntegerField()),
                ('definition_history', models.CharField(max_length=24)),
                ('response_sequence', models.PositiveBigIntegerField()),
                ('answers_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('hash_version', models.PositiveSmallIntegerField()),
                ('original_answers', models.JSONField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='synced_source', to='feedback.feedbacksubmission')),
            ],
        ),
    ]
