# Generated by Django 6.0.8 on 2026-10-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsync', '0002_pendingack_surveysyncstate_syncedsubmissionsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudlink',
            name='inbox_status',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
