# Generated by Django 6.0.8 on 2026-10-03 04:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsync', '0003_cloudlink_inbox_status'),
        ('feedback', '0021_feedbacksubmission_respondent_ref_survey_inbox_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysyncstate',
            name='cloud_publish_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveysyncstate',
            name='local_publish_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ResultUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('publish_sequence', models.PositiveBigIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('content', models.JSONField()),
                ('published_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '待上傳'), ('uploaded', '已上傳'), ('stale', '過期'), ('failed', '失敗')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_uploads', to='feedback.survey')),
            ],
        ),
    ]
