# Generated by Django 6.0.3 on 2026-04-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_convert_access_mode_to_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="improvementdispatch",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
