# Generated by Django 6.0.3 on 2026-05-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_add_is_read_to_improvementdispatch"),
        ("feedback", "0009_merge_20260428_2019"),
    ]

    operations = []
