# Generated by Django 6.0.3 on 2026-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_remove_answer_analysis_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementdispatch',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
