# Generated by Django 6.0.3 on 2026-08-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0010_merge_20260505_2155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="improvementupdate",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="improvements",
                to="feedback.survey",
            ),
        ),
        migrations.CreateModel(
            name="SurveyAIReportSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_fingerprint", models.CharField(max_length=64)),
                ("snapshot_schema_version", models.CharField(max_length=32)),
                ("prompt_version", models.CharField(max_length=32)),
                ("model_name", models.CharField(max_length=100)),
                ("source_snapshot", models.JSONField(default=dict)),
                ("ai_report", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "建立快照中"),
                            ("snapshot_ready", "快照完成"),
                            ("generating", "AI 產生中"),
                            ("succeeded", "成功"),
                            ("failed", "失敗"),
                        ],
                        max_length=24,
                    ),
                ),
                ("response_count", models.PositiveIntegerField(default=0)),
                ("analysis_coverage", models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ("source_latest_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("generation_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("fingerprint_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_report_snapshots",
                        to="feedback.survey",
                    ),
                ),
            ],
            options={
                "db_table": "feedback_survey_ai_report_snapshots",
                "indexes": [
                    models.Index(
                        fields=["survey", "status", "generated_at"],
                        name="fb_ai_survey_status_gen_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "survey",
                            "data_fingerprint",
                            "snapshot_schema_version",
                            "prompt_version",
                            "model_name",
                        ),
                        name="uniq_survey_ai_report_version",
                    )
                ],
            },
        ),
    ]
