# Generated by Django 6.0.3 on 2026-08-13 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def record_existing_improvements(apps, schema_editor):
    ImprovementUpdate = apps.get_model("feedback", "ImprovementUpdate")
    ImprovementStatusHistory = apps.get_model("feedback", "ImprovementStatusHistory")
    ImprovementUpdate.objects.all().update(status="planned")
    ImprovementStatusHistory.objects.bulk_create(
        [
            ImprovementStatusHistory(
                improvement_id=improvement_id,
                from_status="",
                to_status="planned",
            )
            for improvement_id in ImprovementUpdate.objects.values_list("id", flat=True).iterator()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0012_ai_analysis_stages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImprovementStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("planned", "已規劃"),
                            ("in_progress", "進行中"),
                            ("completed", "已完成"),
                            ("archived", "已封存"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="improvementupdate",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="improvementupdate",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="improvementupdate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_improvements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="improvementupdate",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="improvementupdate",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="improvementupdate",
            name="priority",
            field=models.CharField(
                choices=[("high", "高優先"), ("medium", "中優先"), ("low", "低優先")],
                default="medium",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="improvementupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("planned", "已規劃"),
                    ("in_progress", "進行中"),
                    ("completed", "已完成"),
                    ("archived", "已封存"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="improvementupdate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="improvementupdate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_improvements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="improvementupdate",
            name="send_global_notice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="improvementupdate",
            index=models.Index(
                fields=["survey", "status", "-updated_at"],
                name="fb_imp_survey_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="improvementupdate",
            index=models.Index(
                fields=["status", "due_date"], name="fb_imp_status_due_idx"
            ),
        ),
        migrations.AddField(
            model_name="improvementstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="improvement_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="improvementstatushistory",
            name="improvement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="feedback.improvementupdate",
            ),
        ),
        migrations.RunPython(record_existing_improvements, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="improvementupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("planned", "已規劃"),
                    ("in_progress", "進行中"),
                    ("completed", "已完成"),
                    ("archived", "已封存"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="improvementstatushistory",
            index=models.Index(
                fields=["improvement", "-changed_at"], name="fb_imp_history_idx"
            ),
        ),
    ]
