# Generated by Django 6.0.3 on 2026-08-13 22:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_dispatch_state(apps, schema_editor):
    ImprovementDispatch = apps.get_model("feedback", "ImprovementDispatch")
    for dispatch in ImprovementDispatch.objects.select_related("submission").iterator():
        update_fields = []
        if dispatch.sent_at is not None and dispatch.delivery_status != "sent":
            dispatch.delivery_status = "sent"
            update_fields.append("delivery_status")
        if dispatch.submission_id and dispatch.submission.user_id:
            dispatch.recipient_user_id = dispatch.submission.user_id
            update_fields.append("recipient_user")
        if update_fields:
            dispatch.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0013_improvement_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="improvementdispatch",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="improvementdispatch",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="improvementdispatch",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "等待寄送"),
                    ("sending", "寄送中"),
                    ("sent", "已寄送"),
                    ("failed", "寄送失敗"),
                ],
                default="sent",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="improvementdispatch",
            name="error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="improvementdispatch",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="improvementdispatch",
            name="recipient_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="improvementdispatch",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="improvement_dispatches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="improvementdispatch",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="improvementdispatch",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatches",
                to="feedback.feedbacksubmission",
            ),
        ),
        migrations.RunPython(preserve_legacy_dispatch_state, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="improvementdispatch",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "等待寄送"),
                    ("sending", "寄送中"),
                    ("sent", "已寄送"),
                    ("failed", "寄送失敗"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ImprovementNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("global", "所有符合通知條件的顧客"),
                            ("survey_respondents", "這份問卷的符合條件填答者"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("sending", "寄送中"),
                            ("sent", "已寄送"),
                            ("partially_sent", "部分成功"),
                            ("failed", "寄送失敗"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "confirmation_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("content_version", models.PositiveIntegerField(default=1)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_improvement_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_improvement_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "improvement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notices",
                        to="feedback.improvementupdate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="improvementdispatch",
            name="notice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatches",
                to="feedback.improvementnotice",
            ),
        ),
        migrations.AddIndex(
            model_name="improvementdispatch",
            index=models.Index(
                fields=["notice", "delivery_status"], name="fb_dispatch_notice_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="improvementdispatch",
            index=models.Index(
                fields=["recipient_user", "is_read", "-sent_at"],
                name="fb_dispatch_user_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="improvementdispatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("notice__isnull", False)),
                fields=("notice", "recipient_key"),
                name="uniq_notice_recipient",
            ),
        ),
        migrations.AddConstraint(
            model_name="improvementdispatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("notice__isnull", True),
                    ("submission__isnull", False),
                ),
                fields=("improvement", "submission"),
                name="uniq_legacy_imp_submission",
            ),
        ),
        migrations.AddIndex(
            model_name="improvementnotice",
            index=models.Index(
                fields=["improvement", "status", "-created_at"],
                name="fb_notice_imp_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="improvementnotice",
            index=models.Index(
                fields=["status", "-updated_at"], name="fb_notice_status_idx"
            ),
        ),
    ]
