# Generated by Django 6.0.8 on 2026-09-05 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_external_dataset_import_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnalysisState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_version', models.PositiveBigIntegerField(default=0)),
                ('config_version', models.PositiveBigIntegerField(default=0)),
                ('pipeline_version', models.CharField(blank=True, max_length=64)),
                ('published_display_payload', models.JSONField(blank=True, default=dict)),
                ('published_ai_payload', models.JSONField(blank=True, default=dict)),
                ('publication_manifest', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_ai_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_ai_state_rows', to='feedback.surveyaianalysisstage')),
                ('published_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_state_rows', to='feedback.surveyaireportsnapshot')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_state', to='feedback.survey')),
            ],
            options={
                'db_table': 'feedback_survey_analysis_states',
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('answers', '問卷回覆'), ('external', '外部資料表')], default='answers', max_length=16)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('source_version', models.CharField(blank=True, max_length=255)),
                ('executor', models.CharField(choices=[('deterministic', '統計與文字'), ('ai', 'AI 綜合分析')], default='deterministic', max_length=16)),
                ('input_version', models.PositiveBigIntegerField()),
                ('config_version', models.PositiveBigIntegerField()),
                ('pipeline_version', models.CharField(max_length=64)),
                ('input_fingerprint', models.CharField(blank=True, max_length=64)),
                ('requested_stages', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', '等待處理'), ('running', '處理中'), ('succeeded', '成功'), ('failed', '失敗'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('worker_id', models.CharField(blank=True, max_length=128)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('result_manifest', models.JSONField(blank=True, default=dict)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='feedback.survey')),
            ],
            options={
                'db_table': 'feedback_analysis_jobs',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['status', 'available_at', 'created_at'], name='fb_job_claim_idx'), models.Index(fields=['survey', 'status', '-created_at'], name='fb_job_survey_idx'), models.Index(fields=['status', 'lease_expires_at'], name='fb_job_lease_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('survey', 'source_kind', 'source_ref', 'executor'), name='fb_job_one_pending_source')],
            },
        ),
    ]
