# Generated by Django 6.0.8 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0016_surveyanalysisstate_analysisjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetimportbatch",
            name="random_seed",
            field=models.IntegerField(blank=True, default=42, null=True),
        ),
        migrations.AlterField(
            model_name="datasetimportbatch",
            name="requested_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
