# Generated by Django 6.0.8 on 2026-09-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_feedback_schema_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ref', models.CharField(max_length=255)),
                ('source_version', models.CharField(max_length=255)),
                ('source_revision', models.CharField(max_length=128)),
                ('cleaning_version', models.CharField(max_length=100)),
                ('content_sha256', models.CharField(max_length=64)),
                ('schema_sha256', models.CharField(blank=True, max_length=64)),
                ('mapping_key', models.SlugField(max_length=100)),
                ('mapping_version', models.CharField(max_length=100)),
                ('row_count', models.PositiveBigIntegerField()),
                ('source_latest_at', models.DateTimeField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback_external_dataset_versions',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnalysisSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('answers', '問卷回覆'), ('external', '外部資料表')], default='answers', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_external_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_sources', to='feedback.externaldatasetversion')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_source', to='feedback.survey')),
            ],
            options={
                'db_table': 'feedback_survey_analysis_sources',
            },
        ),
        migrations.AddField(
            model_name='externaldatasetversion',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_versions', to='feedback.surveyanalysissource'),
        ),
        migrations.AddIndex(
            model_name='externaldatasetversion',
            index=models.Index(fields=['source_ref', 'source_version'], name='fb_external_version_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaldatasetversion',
            constraint=models.UniqueConstraint(fields=('source', 'source_ref', 'source_version'), name='fb_external_dataset_version_uniq'),
        ),
    ]
