# Generated by Django 6.0.8 on 2026-10-03 00:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


def fill_uuids(apps, schema_editor):
    for model_name in ("Survey", "Question"):
        model = apps.get_model("feedback", model_name)
        for pk in model.objects.values_list("pk", flat=True):
            model.objects.filter(pk=pk).update(uuid=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0001_initial'),
        ('feedback', '0019_externaldatasetversion_surveyanalysissource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_received_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='definition_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='owner_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='cloudapi.nodedevice'),
        ),
        migrations.AddField(model_name="survey", name="uuid", field=models.UUIDField(null=True, editable=False)),
        migrations.AddField(model_name="question", name="uuid", field=models.UUIDField(null=True, editable=False)),
        migrations.RunPython(fill_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="survey", name="uuid", field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
        ),
        migrations.AlterField(
            model_name="question", name="uuid", field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
        ),
    ]
