# Generated by Django 6.0.8 on 2026-10-03 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_question_has_received_answer_question_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksubmission',
            name='respondent_ref',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='survey',
            name='inbox_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='response_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbacksubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
