# Generated by Django 6.0.8 on 2026-10-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_feedbacksubmission_respondent_ref_survey_inbox_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanalysisstate',
            name='analyzed_through_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyanalysisstate',
            name='definition_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyanalysisstate',
            name='publish_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyanalysisstate',
            name='published_upload_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
