# Generated by Django 6.0.8 on 2026-10-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0022_surveyanalysisstate_analyzed_through_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice_codes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='definition_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='display',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='question',
            name='next_choice_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_max_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_min_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='score_start',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='survey',
            name='analysis_definition_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='next_question_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='survey',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='published_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
