from django.urls import path

from .views import (
    CustomerHomeView,
    CustomerNotificationsView,
    DashboardView,
    HomeView,
    ImprovementCreateView,
    ImprovementListView,
    KeywordCategoryCreateView,
    KeywordCategoryDeleteView,
    MarkNoticeReadView,
    NoticeCenterView,
    NoticeDetailView,
    StatsOverviewView,
    SurveyBuilderView,
    SurveyCategoryCreateView,
    SurveyCategoryDeleteView,
    SurveyCreateView,
    SurveyDeleteView,
    SurveyDetailView,
    SurveyManagerView,
    SurveyQRCodeView,
    SurveySubmitSuccessView,
    TextAnalysisView,
)

app_name = "feedback"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("app/", CustomerHomeView.as_view(), name="customer-home"),
    path("app/notifications/", CustomerNotificationsView.as_view(), name="customer-notifications"),
    path("app/notifications/<int:pk>/read/", MarkNoticeReadView.as_view(), name="notice-mark-read"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("dashboard/forms/", SurveyManagerView.as_view(), name="survey-manager"),
    path("dashboard/categories/create/", SurveyCategoryCreateView.as_view(), name="category-create"),
    path("dashboard/categories/<int:pk>/delete/", SurveyCategoryDeleteView.as_view(), name="category-delete"),
    path("dashboard/forms/new/", SurveyCreateView.as_view(), name="survey-create"),
    path("dashboard/forms/<slug:slug>/builder/", SurveyBuilderView.as_view(), name="survey-builder"),
    path("dashboard/forms/<slug:slug>/qrcode/", SurveyQRCodeView.as_view(), name="survey-qrcode"),
    path("dashboard/forms/<slug:slug>/delete/", SurveyDeleteView.as_view(), name="survey-delete"),
    path("dashboard/stats/", StatsOverviewView.as_view(), name="stats-overview"),
    path("dashboard/text-analysis/", TextAnalysisView.as_view(), name="text-analysis"),
    path("dashboard/keyword-categories/create/", KeywordCategoryCreateView.as_view(), name="keyword-category-create"),
    path("dashboard/keyword-categories/<int:pk>/delete/", KeywordCategoryDeleteView.as_view(), name="keyword-category-delete"),
    path("dashboard/improvements/", ImprovementListView.as_view(), name="improvement-list"),
    path("dashboard/notices/", NoticeCenterView.as_view(), name="notice-center"),
    path("dashboard/notices/<int:pk>/", NoticeDetailView.as_view(), name="notice-detail"),
    path("survey/<slug:slug>/", SurveyDetailView.as_view(), name="survey-detail"),
    path("survey/<slug:slug>/success/", SurveySubmitSuccessView.as_view(), name="survey-success"),
    path("survey/<slug:slug>/improvement/new/", ImprovementCreateView.as_view(), name="improvement-create"),
]
