from django.urls import path

from .views import (
    AIImprovementDraftCreateView,
    AIStageImprovementDraftCreateView,
    AIReportGenerateView,
    AIReportSnapshotView,
    AIReportStatusView,
    AIStageGenerateView,
    AIStagePipelineStatusView,
    CustomerHomeView,
    CustomerNotificationsView,
    DashboardView,
    HomeView,
    ImprovementCreateView,
    ImprovementDetailView,
    ImprovementNoticeCreateView,
    ImprovementNoticeDetailView,
    ImprovementNoticePreviewView,
    ImprovementNoticeRetryView,
    ImprovementNoticeSendView,
    ImprovementNoticeUpdateView,
    ImprovementListView,
    ImprovementStatusTransitionView,
    ImprovementUpdateView,
    KeywordCategoryCreateView,
    KeywordCategoryDeleteView,
    KeywordCategoryUpdateView,
    MarkNoticeReadView,
    NoticeCenterView,
    NoticeDetailView,
    StatsOverviewView,
    SurveyBuilderView,
    SurveyCategoryCreateView,
    SurveyCategoryDeleteView,
    SurveyCreateView,
    SurveyDeleteView,
    SurveyDetailView,
    SurveyManagerView,
    SurveyQRCodeView,
    SurveySubmitSuccessView,
    TextAnalysisView,
)

app_name = "feedback"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("app/", CustomerHomeView.as_view(), name="customer-home"),
    path("app/notifications/", CustomerNotificationsView.as_view(), name="customer-notifications"),
    path("app/notifications/<int:pk>/read/", MarkNoticeReadView.as_view(), name="notice-mark-read"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("dashboard/ai-reports/<slug:slug>/", AIReportStatusView.as_view(), name="ai-report-status"),
    path(
        "dashboard/ai-reports/<slug:slug>/stages/",
        AIStagePipelineStatusView.as_view(),
        name="ai-stage-status",
    ),
    path(
        "dashboard/ai-reports/<slug:slug>/snapshot/",
        AIReportSnapshotView.as_view(),
        name="ai-report-snapshot",
    ),
    path(
        "dashboard/ai-reports/<slug:slug>/snapshots/<int:pk>/generate/",
        AIReportGenerateView.as_view(),
        name="ai-report-generate",
    ),
    path(
        "dashboard/ai-reports/<slug:slug>/snapshots/<int:pk>/stages/<str:stage_type>/generate/",
        AIStageGenerateView.as_view(),
        name="ai-stage-generate",
    ),
    path("dashboard/forms/", SurveyManagerView.as_view(), name="survey-manager"),
    path("dashboard/categories/create/", SurveyCategoryCreateView.as_view(), name="category-create"),
    path("dashboard/categories/<int:pk>/delete/", SurveyCategoryDeleteView.as_view(), name="category-delete"),
    path("dashboard/forms/new/", SurveyCreateView.as_view(), name="survey-create"),
    path("dashboard/forms/<slug:slug>/builder/", SurveyBuilderView.as_view(), name="survey-builder"),
    path("dashboard/forms/<slug:slug>/qrcode/", SurveyQRCodeView.as_view(), name="survey-qrcode"),
    path("dashboard/forms/<slug:slug>/delete/", SurveyDeleteView.as_view(), name="survey-delete"),
    path("dashboard/stats/", StatsOverviewView.as_view(), name="stats-overview"),
    path("dashboard/text-analysis/", TextAnalysisView.as_view(), name="text-analysis"),
    path("dashboard/keyword-categories/create/", KeywordCategoryCreateView.as_view(), name="keyword-category-create"),
    path("dashboard/keyword-categories/<int:pk>/update/", KeywordCategoryUpdateView.as_view(), name="keyword-category-update"),
    path("dashboard/keyword-categories/<int:pk>/delete/", KeywordCategoryDeleteView.as_view(), name="keyword-category-delete"),
    path("dashboard/improvements/", ImprovementListView.as_view(), name="improvement-list"),
    path("dashboard/improvements/<int:pk>/", ImprovementDetailView.as_view(), name="improvement-detail"),
    path("dashboard/improvements/<int:pk>/edit/", ImprovementUpdateView.as_view(), name="improvement-update"),
    path(
        "dashboard/improvements/<int:pk>/status/",
        ImprovementStatusTransitionView.as_view(),
        name="improvement-status",
    ),
    path(
        "dashboard/improvements/<int:pk>/notices/new/",
        ImprovementNoticeCreateView.as_view(),
        name="notice-batch-create",
    ),
    path(
        "dashboard/notices/batches/<int:pk>/",
        ImprovementNoticeDetailView.as_view(),
        name="notice-batch-detail",
    ),
    path(
        "dashboard/notices/batches/<int:pk>/edit/",
        ImprovementNoticeUpdateView.as_view(),
        name="notice-batch-update",
    ),
    path(
        "dashboard/notices/batches/<int:pk>/preview/",
        ImprovementNoticePreviewView.as_view(),
        name="notice-batch-preview",
    ),
    path(
        "dashboard/notices/batches/<int:pk>/send/",
        ImprovementNoticeSendView.as_view(),
        name="notice-batch-send",
    ),
    path(
        "dashboard/notices/batches/<int:pk>/retry/",
        ImprovementNoticeRetryView.as_view(),
        name="notice-batch-retry",
    ),
    path("dashboard/notices/", NoticeCenterView.as_view(), name="notice-center"),
    path("dashboard/notices/<int:pk>/", NoticeDetailView.as_view(), name="notice-detail"),
    path("survey/<slug:slug>/", SurveyDetailView.as_view(), name="survey-detail"),
    path("survey/<slug:slug>/success/", SurveySubmitSuccessView.as_view(), name="survey-success"),
    path("survey/<slug:slug>/improvement/new/", ImprovementCreateView.as_view(), name="improvement-create"),
    path(
        "survey/<slug:slug>/improvement/ai/<int:snapshot_id>/<slug:draft_id>/",
        AIImprovementDraftCreateView.as_view(),
        name="ai-improvement-draft",
    ),
    path(
        "dashboard/improvements/<slug:slug>/ai/<int:stage_id>/<uuid:draft_id>/new/",
        AIStageImprovementDraftCreateView.as_view(),
        name="ai-stage-improvement-draft",
    ),
]
