# Generated by Django 6.0.8 on 2026-09-30 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '節點安裝狀態',
                'verbose_name_plural': '節點安裝狀態',
            },
        ),
        migrations.CreateModel(
            name='NodeAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '稽核紀錄',
                'verbose_name_plural': '稽核紀錄',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
