# Generated by Django 6.0.8 on 2026-10-03 00:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_clock(apps, schema_editor):
    apps.get_model("cloudapi", "ChangeClock").objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0019_externaldatasetversion_surveyanalysissource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveBigIntegerField(default=0)),
                ('pruned_through', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NodeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='名稱')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', '啟用'), ('revoked', '已撤銷')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '本機節點裝置',
                'verbose_name_plural': '本機節點裝置',
            },
        ),
        migrations.CreateModel(
            name='SurveyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveBigIntegerField(unique=True)),
                ('definition_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='feedback.survey')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='SurveyDefinitionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definition_revisions', to='feedback.survey')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('survey', 'version'), name='cloudapi_revision_survey_version_uniq')],
            },
        ),
        migrations.RunPython(create_clock, migrations.RunPython.noop),
    ]
