# Generated by Django 6.0.8 on 2026-10-03 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0001_initial'),
        ('feedback', '0021_feedbacksubmission_respondent_ref_survey_inbox_since_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied_count', models.PositiveBigIntegerField(default=0)),
                ('occupied_bytes', models.PositiveBigIntegerField(default=0)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_counter', to='cloudapi.nodedevice')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_uuid', models.UUIDField(unique=True)),
                ('submitted_at', models.DateTimeField()),
                ('consent_follow_up', models.BooleanField(default=False)),
                ('definition_version', models.PositiveIntegerField()),
                ('response_sequence', models.PositiveBigIntegerField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', '已收件'), ('synced', '已同步'), ('quarantined', '衝突'), ('abandoned', '已放棄')], default='received', max_length=12)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_known_improvement_status', models.CharField(blank=True, max_length=20)),
                ('quarantine_reason', models.CharField(blank=True, max_length=32)),
                ('resolution', models.CharField(blank=True, choices=[('', '無'), ('unresolved', '待處理'), ('requeued', '已放回'), ('abandoned', '已放棄')], default='', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='cloudapi.nodedevice')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='feedback.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InboxSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_uuid', models.UUIDField(unique=True)),
                ('envelope', models.JSONField()),
                ('answers_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('hash_version', models.PositiveSmallIntegerField(default=1)),
                ('payload_version', models.PositiveSmallIntegerField(default=1)),
                ('size_bytes', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', '待收'), ('quarantined', '隔離')], default='pending', max_length=12)),
                ('quarantine_reason', models.CharField(blank=True, max_length=32)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_items', to='cloudapi.nodedevice')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='feedback.survey')),
            ],
            options={
                'indexes': [models.Index(fields=['node', 'state', 'received_at', 'submission_uuid'], name='cloudapi_inbox_fetch_idx')],
            },
        ),
    ]
