# Generated by Django 6.0.8 on 2026-10-03 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0002_inboxcounter_submissionreceipt_inboxsubmission'),
        ('feedback', '0022_surveyanalysisstate_analyzed_through_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_uuid', models.UUIDField(unique=True)),
                ('publish_sequence', models.PositiveBigIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('definition_version', models.PositiveBigIntegerField()),
                ('analyzed_through_sequence', models.PositiveBigIntegerField()),
                ('applied', models.BooleanField(default=False)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_records', to='cloudapi.nodedevice')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='feedback.survey')),
            ],
        ),
    ]
